### ISSUE TITLE
Configure ReadHeaderTimeout in http.Server

### ISSUE THREAD

**Issue by MaxMcAdam** [open-horizon/edge-sync-service#142]
From static scan: Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server. The server is started is in edge-sync-service/core/base/http.go on line 24.

**Comment by johnwalicki** [comment]
https://github.com/open-horizon/edge-sync-service/blob/e76c2d0fc5c73ff0f72418fbd4553655dd6c16d8/core/base/http.go#L24
