### ISSUE TITLE
LF-Home Edge Integration with sync service issues

### ISSUE THREAD

**Issue by Nitu-coder** [open-horizon/edge-sync-service#39]
Hello,
I m working on cross collaboration of Home edge which comes under LF-Edge umbrella with open Horizon. I m trying to use the sync service to enable the sync mechanism of ML models in my edge computing for cloud. In the same regard, i m trying to build the service locally and check for transfer of models from ESS to CSS and vice versa. I have following issues in it

1. Can Sync service operate independently without exchange api server and agbot to the service needed in Home Edge?
2. I m trying to build the service it builds in docker,.Can i build it locally?

Can you please help me with this issue.

**Comment by dabooz** [comment]
1. It can operate independently, it was designed an implemented to be a re-usable entity. An example of how to use this component standalone is found here: https://github.com/open-horizon/edge-sync-service/tree/master/samples/send-receive-files. However, without the openhorizon management hub, you will not get the benefit of automatic routing and delivery of the objects. You will need logic to manipulate the destination fields of the object definition.
2. You can build it locally, see the project level read me.

**Comment by Nitu-coder** [comment]
> 1. It can operate independently, it was designed and implemented to be a re-usable entity. An example of how to use this component standalone is found here: https://github.com/open-horizon/edge-sync-service/tree/master/samples/send-receive-files. However, without the openhorizon management hub, you will not get the benefit of automatic routing and delivery of the objects. You will need logic to manipulate the destination fields of the object definition.
> 2. You can build it locally, see the project level read me.

Ok, Thanks alot, that will be helpful. but any documentation to pair the edge sync service with exchange and agbot at the cloud side?

**Comment by dabooz** [comment]
See https://github.com/edgexfoundry-holding/open-horizon-integration/tree/master/hub specifically in the section called 'High Level Steps', steps 1 and 2 will help you get an open horizon hub running, including a CSS on the cloud side.
